FORMAT: 1A
HOST: http://askfastmarket.appspot.com/products/broadcastnew

# Ask Fast Marketplace

# Group Getting started

The marketplace is an extension to the Ask Fast API. This gives you the possibility to host your questions and answers on our servers. so you do not have to program anything on the server side. 
Send your first message
The base URL is: http://askfastmarket.appspot.com.

To send your first message you have to give some information to the Market place. This includes the people whom you want to send you message to, the method of senden, etc. The example gives the bare minimum that the server needs to send a message. If you like to add more specific functionality all the parameters can be found at the documentation
To send the request you send a json with the question and the addresses to the server. 

## send first message [/appid={appid}&instanceid={instanceid}]

### send message [POST]

+ parameters
    + appid (required, String, `xxxxxxxx`) ... String `appid` of your aplication can be found in the developer page
    + instanceid (required, String, `xxxxx`) ... String `instanceid` of your aplication can be found in the developer page