FORMAT: 1A
HOST: http://askfastmarket.appspot.com/products/broadcastnew

# Ask Fast Marketplace

# Group Getting started

The marketplace is an extension to the Ask Fast API. This gives you the possibility to host your questions and answers on our servers. so you do not have to program anything on the server side. 
Send your first message
The base URL is: http://askfastmarket.appspot.com.

To send your first message you have to give some information to the Market place. This includes the people whom you want to send you message to, the method of senden, etc. The example gives the bare minimum that the server needs to send a message. If you like to add more specific functionality all the parameters can be found at the documentation
To send the request you send a json with the question and the addresses to the server. 

## send first message [/appid={appid}&instanceid={instanceid}]

### send message [POST]

Headers:

Bearer token

post body:
``
    {

    "addresses": {
    
        "EMAIL": [
        
            {
            
                "address": "test@email.com"
                
            }
            
        ],
        
        "SMS": [
        
            {
            
                "address": "06000000000"
                
            }
            
        ]
        
    },
    
    "senderName": "vincent",
    
    "message": "post man test",
    
    "retryMethod": "MANUAL",
    
    "retryLimit": 1,
    
     "emailSubject": "post man test"
     }
``


Addresses (arrray)of addapters (SMS, EMAIL, etc) each array should have an array of adresses in the format: “adress”:”test@email.com”.

senderName: (string)
The name you want to appear to be the sender of the message
message: (string)
The body of the message. This should be short for sms texting. 
retryMethod: (string)
AUTO or MANUAL -> if auto the system will repead as many times as set in the retry limit until there is a awnswer.
retryLimit: (number)
Amout of times the server sends the message if there is no response
broadcastName: (string)
Custom name to describe this broadcast. 
emailSubject: (string) 
Only used for emailing, this sets the subject of the email.

+ parameters
    + appid (required, String, `xxxxxxxx`) ... String `appid` of your aplication can be found in the developer page
    + instanceid (required, String, `xxxxx`) ... String `instanceid` of your aplication can be found in the developer page

+ response 200 (aplication/json)
    
        {
        "broadcast": {
        "addresses": {
            "SMS": [
                {
                    "address": "number",
                    "adapterId": "5cc9c390-d1fb-11e3-9807-061c2777aa3c",
                    "addressInfo": "Netherlands: 0031624107729",
                    "contactName": ""
                }
            ],
            "EMAIL": [
                {
                    "address": "email",
                    "adapterId": "53dffd50-d203-11e3-b959-061c2777aa3c",
                    "contactName": ""
                }
            ]
        },
            "adapterList": {},
            "language": "nl-nl",
            "senderName": "SenderName",
            "emailSubject": "emailSubjectt",
            "message": "Your message",
            "broadcastName": "Your broadcast name",
            "questionType": "[OPEN | COMMENT \ CLOSED] ",
            "answers": [],
            "timeStamp": 1399627155706,
            "retryCount": 0,
            "retryLimit": 1,
            "retryMethod": "MANUAL"
        },
            "id": 6246531984261120,
            "broadcastCount": 2,
            "retryInfos": {},
            "ownerKey": "vincent"
        }
